---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS litters data.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not other

```{r}
select(litters_df, group, litter_number)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns
(select the column that I want to keep and in the mean while renaming those)
```{r}
select(litters_df, GROUP = group, LITTER_NUMBER = litter_number)
```

rename without select
```{r}
rename(litters_df, GROUP = group, LITTER_NUMBER = litter_number)
```

Helper functions

Select Helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

relocate did not work??

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod 8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod 8"))
```



